name: CI - Build & Push Docker Images

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # ---- Login to DockerHub ----
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ---- Build & Push BACKEND ----
      - name: Build backend image
        working-directory: ./spoolr-core
        run: |
          docker build -t $DOCKERHUB_USERNAME/spoolr-core:latest .

      - name: Push backend image
        run: |
          docker push $DOCKERHUB_USERNAME/spoolr-core:latest

      # ---- Build & Push FRONTEND ----
      - name: Build frontend image
        working-directory: ./spoolr-frontend
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_API_URL=http://spoolr-core:8080 \
            -t $DOCKERHUB_USERNAME/spoolr-frontend:latest .

      - name: Push frontend image
        run: |
          docker push $DOCKERHUB_USERNAME/spoolr-frontend:latest
